name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Installe Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # 3. Authentification à npm
      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n@electron-covalent:registry=https://registry.npmjs.org/" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm ci

      # 4. Publication npm
      - name: Publishing
        run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
