name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installe Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # 3. Authentification à npm
      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n@electron-covalent:registry=https://registry.npmjs.org/" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Dependencies installation
        run: npm ci

      - name: Build
        run: npm run build

      - name: Testing core
        run: npm run test:core

      - name: Testing render
        run: npm run test:render

      # 4. Publication npm
      - name: Publishing
        run: npm run release
